# Generated by Django 4.2.8 on 2023-12-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_subscription_field_a_subscription_field_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='field_a',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='field_b',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
